### PR TITLE
Add copy to selector

### PR DESCRIPTION
**Pull request by riusricardo**
Adds copy button to selector

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
image

Great idea!

Dumb question: What Substrate is this supposed to work against? Using it with alpha.8 gave me:
`Unknown signed extensions CheckTxVersion found, treating them as no-efect`

**Comment by riusricardo** [comment]
Right @JoshOrndorff . I'll update the dependencies to get rid of that warning.

**Comment by jimmychu0807** [comment]
@riusricardo I think I have added that feature already. Isn't it?

**Comment by riusricardo** [comment]
@jimmychu0807 You have it next to the balances but not in the account selector component.

**Comment by jimmychu0807** [comment]
I see. Cool with that.

**Pull request merged**
