### PR TITLE
Solution of Transfer of tokens don't work #279

### PR DESCRIPTION
**Pull request by fzeeshan**
There is function call in UI that needs to be changed so the tokens can be transferred, it solves Transfer of tokens don't work #279

### CODE REVIEW

**Comment by fzeeshan** [comment]
the changes have been tested by myself and few other users.

**Review by sheshnath-at-knoldus — COMMENTED** [review]
it works after changing callable: 'transfer' to callable: 'transferAllowDeath',

**Review by NXHM — APPROVED** [review]
I tried in my computer and it works, it transfers tokens

**Comment by fzeeshan** [comment]
My change works but they are not letting me merge it

**Review by NXHM — APPROVED** [review]

**Review by falcucci — APPROVED** [review]

**Review by fzeeshan — COMMENTED** [review]
submitting #279 solution

**Comment by fzeeshan** [comment]
I'm new to this, so not sure if there is something I have to do on my side?

**Comment by falcucci** [comment]
> I'm new to this, so not sure if there is something I have to do on my side?

not actually, the maintainers should review it and merge. but seems like the repo is quiet  for too long by now.

leave it and wait

**Review by NXHM — APPROVED** [review]

**Comment by NXHM** [comment]
i don´t know, i think we should wait to @sheshnath-at-knoldus review

**Comment by sacha-l** [comment]
I believe @DrW3RK can help get this merged 👀

**Review by DrW3RK — APPROVED** [review]

**Pull request merged**
