### PR TITLE
Config with semistandard eslint and passing all tests

### PR DESCRIPTION
**Pull request by jimmychu0807**
Updated to use strict semistandard. 

According to [doc](https://www.npmjs.com/package/eslint-config-semistandard), there are quite some dev-dependencies to be installed to make this work.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
Should we add a follow up issue to enable CI on this repository?

**Comment by riusricardo** [comment]
@shawntabrizi CI will be very helpful on this repo for testing builds. Are you thinking on creating React tests? or just want to validate that it is not broken.

**Comment by shawntabrizi** [comment]
https://github.com/substrate-developer-hub/substrate-front-end-template/issues/10

Ideally we create react tests, and even some more practical ones where we connect to the `dev-node` and make transactions??

**Comment by jimmychu0807** [comment]
@shawntabrizi 
You don't need to do anything, when running `yarn start`, it compile and lint your code.

If you want to let the linter auto-fix (which pretty much fix 90% of issues), run `yarn semistandard --fix`.

**Comment by JoshOrndorff** [comment]
@jimmychu0807 Hope this isn't a dumb question, but I can't seem to get this working.

1. Pull latest master
2. Introduce some should-be linting errors (like missing semicolons, double-quoted strings, etc)
3. Save files
4. `yarn start`
5. No errors or warnings in the terminal or console

I remember you [previously said](https://github.com/substrate-developer-hub/substrate-front-end-template/pull/43#issuecomment-536387355) my attempt was only for editor integration is that true here too? If so, how will we be able to use this with CI?

**Comment by jimmychu0807** [comment]
@JoshOrndorff 
- right, you need to do a `yarn install`, to install the new dependencies. So it works for you now?
- I was wrong. With the new `EXTEND_ESLINT=true`, the linting check actually also reflects in browser and terminal. And semistandard by default returns error (not warning) when failing their tests. 
- you can also do `yarn lint` now just to do linting. So we can put linting check as part of the CI workflow.

**Comment by JoshOrndorff** [comment]
Yes it works for me now including browser and terminal. Great job!

**Pull request merged**
