### PR TITLE
Fix linting from e740f1dc

### PR DESCRIPTION
**Pull request by JoshOrndorff**
No logic changes, just formatting.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
i got no linting warnings when running `yarn start` or `yarn build` here.

**Comment by jimmychu0807** [comment]
@shawntabrizi just to get rid of the obvious. Did you do `yarn install` after getting the latest code?

**Comment by shawntabrizi** [comment]
No I did not. It works now.

Although have I found that eslint is not so "deterministic".
For example my auto-formatter in VS code makes suggestions which are different than what is sometimes in the existing code, but is still valid and clean for eslint.

In which case, it seems we are back to the original problem.

**Comment by JoshOrndorff** [comment]
I think there are two solutions to that which are not mutually exclusive.

1. Don't reformat code that isn't relevant to your PR.
2. Add stricter linting rules so there are fewer ambiguous cases.

I'll definitely stick to 1 and I'm happy to review PRs that implement 2.

**Comment by shawntabrizi** [comment]
In general, when I work with a file, I pretty mindlessly do `ctrl + a, ctrl + k, ctrl + f` which auto formats the whole doc.

I can of course stop this, which I will for this repo, but just wanted to call that out.

**Pull request merged**
