### PR TITLE
Multiple fixes (`monthly-2022-01` tag)

### LINKED ISSUE #209: More descriptive error handling than `{ "isTrusted": true }`
https://github.com/paritytech/subport/issues/266 and many other get
```
Error Connecting to Substrate

{ "isTrusted": true }
```

And no other indication of what might be wrong. Most of the time this is due to simply not having remote connections allowed (the right default) but the vast majority of users are just experimenting with a development setup using this template. Some help to inform them of this common issue would useful!

### LINKED ISSUE #211: Docs: Github about link is not found (404)
The link `https://substrate.dev/substrate-front-end-template/` in the About section of the repository leads to `404`.
You could replace it with e.g. `https://docs.substrate.io/tutorials/v3/create-your-first-substrate-chain/`

Cheers

### PR DESCRIPTION
**Pull request by jimmychu0807**
@sacha-l @NukeManDan

- Remove the traces on custom type and update to based on Node v16.
- Upgrading `react-scripts` to v5. This means now it is using webpack 5. Resume back using `react-app-rewired` to extend the webpack config at `config-overrides.js`.
  - Note the dependency `semantic-ui-css` is pointing to the `master` branch as the latest fix of making it webpack 5 compatible is merged in `master` but not yet released.
- Using `prettier` for code formatting.
- Polkadot-js API have updated to the latest version.
- Refactored current selected account into SubstrateContext, so this info no longer need to be passed from the topmost parent to its children. 

Once this PR is merged, the `main` branch is ready to be tagged as `monthly-2022-01`.

---
close #211
close #209

### CODE REVIEW

**Comment by sacha-l** [comment]
@jimmychu0807  thanks for revising the front-end template here. A couple things:
- I had to manually install `react-app-rewired` 
- I did it using `npm` and then ran `npm install && npm start` and it worked 🎉 
- However, using `yarn` isn't working for me. I get the error log:
```bash
➤ YN0001: │ Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:371:5)
    at PassThrough.onclose (node:internal/streams/end-of-stream:134:30)
    at PassThrough.emit (node:events:390:28)
    at emitCloseNT (node:internal/streams/destroy:145:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
➤ YN0000: └ Completed in 57s 489ms
➤ YN0000: Failed with errors in 57s 492ms
➤ YN0061: source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
sachalansky@Sachas-MacBook-Pro substrate-front-end-template % yarn start  
Internal Error: substrate-front-end-template@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Mk.getCandidates (/Users/sachalansky/Documents/GitHub/substrate-front-end-template/.yarn/releases/yarn-berry.cjs:299:4306)
    at Xc.getCandidates (/Users/sachalansky/Documents/GitHub/substrate-front-end-template/.yarn/releases/yarn-berry.cjs:294:4947)
    at /Users/sachalansky/Documents/GitHub/substrate-front-end-template/.yarn/releases/yarn-berry.cjs:303:7643
    at Gl (/Users/sachalansky/Documents/GitHub/substrate-front-end-template/.yarn/releases/yarn-berry.cjs:242:4003)
    at y (/Users/sachalansky/Documents/GitHub/substrate-front-end-template/.yarn/releases/yarn-berry.cjs:303:7623)
```

**Comment by sacha-l** [comment]
Should we just replace the `yarn` instructions with `npm` ?

**Comment by jimmychu0807** [comment]
@sacha-l Thanks for checking. I found that the issue has been reported with the fix at https://github.com/yarnpkg/berry/issues/3597.

I have applied the fix. Let me know if it works for you now. Thanks.

**Comment by jimmychu0807** [comment]
@sacha-l I am merging this PR for now. Let me know with the last `yarn` fix, if you could successfully run `yarn install` again. Thanks.

**Pull request merged**
