### PR TITLE
Update to alpha.7

### PR DESCRIPTION
**Pull request by danforbes**

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
Did you try submitting a transfer with the updated front end? If so, did the front end correctly decode the event? I was expecting you would have the change the weight type to `u64`.

**Comment by danforbes** [comment]
@JoshOrndorff - you know I did and it _was_ a little weird, but I don't _think_ it was an error that had to do with types. It didn't work at first (I got an error about one of the params to the transfer call not being hex, or something) but then I tried again and it seemed to "just work" :shrug: Not necessarily a great feeling. Would you mind trying on your end with the code I have in this branch and stuff?

**Comment by JoshOrndorff** [comment]
I tried it out with the code in the PR here and it worked (3/3 successes). I also tried it with the new weight type and it also worked. I'm leaning toward including the explicit `"Weight": "u64`. Doing so would be harmless at worst, and fix a bug we haven't encountered yet at best.

**Comment by danforbes** [comment]
Works for me! Maybe just a quick check with Jaco so we feel like we understand why they work either way?

**Pull request merged**
