### PR TITLE
fix for v2.0.1

### PR DESCRIPTION
**Pull request by NukeManDan**
solves https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/835

### CODE REVIEW

**Comment by NukeManDan** [comment]
if we wanted to release a patch version, this solves a minor issue when using 2.0.1 of the node template. 

so a 2.0.1 tag or branch for this for people to pull from would be useful

**Comment by shawntabrizi** [comment]
It should be that Jaco fixes this so that this default?

**Comment by NukeManDan** [comment]
This I have run successfully on a clean build of the node template 2.0.1 running 
Ths minor change to types is all that is needed to solve any errors like #158 are getting

**Comment by NukeManDan** [comment]
@shawntabrizi - sorry I at first missed your reply here, I have tried to run with and without the types.json file specifying

```
{
"Address": "MultiAddress",
"LookupSource": "MultiAddress"
}
```

and an empty {} .

---

I get strange behaviour: on a clean `yarn install` and `yarn start` I get the #158 error, then _with no change to the code_ I stop the server and start again with further no issue, with or without this type specified.

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-front-end-template/issues/158#issuecomment-766763473 reports that you must have the custom types defined, so must have been erroneous on my part with an empty {} for types.json. I have updated the PR to reset to the right commit.

**Review by jimmychu0807 — APPROVED** [review]
Very cool @NukeManDan . Thanks for the fix

**Pull request merged**
